stages:
    - master
    #- desarrollo
    - execsonar

UPD_Master:
    stage: master
    tags:
        - fuentes
    script:
        - cd $RUTA_INTI_FRONT_MAS
        - sudo git pull origin master
    only:
        - master

EjecutarSonar:
    stage: execsonar
    tags:
        - sonar
    script:
        - H:\sonnar\sonar.bat
        
    when: manual
    
    only:
        - master
